[package]
name = "image2ascii"
version = "0.2.2"
edition = "2021"
authors = ["Rik de Goede"]
description = "A simple terminal application to convert an image to ASCII text."

[dependencies]
image = "0.25"